title: "Question "
labels: ["(Question and Answer)"]
body:
  - type: markdown
    attributes:
      value: |
        Ask questions about this project here for answers from project maintainers and/or the community
  - type: textarea
    attributes:
      label: "My question is..."
